// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrabMs4o3UuQwTCVdiwtWp4obzWjjO7Q',
    appId: '1:139586112413:web:1386f7a09037d2649cfd74',
    messagingSenderId: '139586112413',
    projectId: 'instalmate-ffd13',
    authDomain: 'instalmate-ffd13.firebaseapp.com',
    storageBucket: 'instalmate-ffd13.firebasestorage.app',
    measurementId: 'G-G9ESGC09XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCjqVvfn4fuDzFOFsZgI8s4gqe2N95b0',
    appId: '1:139586112413:android:62b804b9ec0f3f769cfd74',
    messagingSenderId: '139586112413',
    projectId: 'instalmate-ffd13',
    storageBucket: 'instalmate-ffd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOk5oiKctUhABjk57fSkVEc0TiYuxWzA0',
    appId: '1:139586112413:ios:3eb421c8e69f45ca9cfd74',
    messagingSenderId: '139586112413',
    projectId: 'instalmate-ffd13',
    storageBucket: 'instalmate-ffd13.firebasestorage.app',
    iosBundleId: 'com.example.installmentHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOk5oiKctUhABjk57fSkVEc0TiYuxWzA0',
    appId: '1:139586112413:ios:3eb421c8e69f45ca9cfd74',
    messagingSenderId: '139586112413',
    projectId: 'instalmate-ffd13',
    storageBucket: 'instalmate-ffd13.firebasestorage.app',
    iosBundleId: 'com.example.installmentHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmrabMs4o3UuQwTCVdiwtWp4obzWjjO7Q',
    appId: '1:139586112413:web:aceffc2368858cbf9cfd74',
    messagingSenderId: '139586112413',
    projectId: 'instalmate-ffd13',
    authDomain: 'instalmate-ffd13.firebaseapp.com',
    storageBucket: 'instalmate-ffd13.firebasestorage.app',
    measurementId: 'G-WB7CS0HQ4C',
  );
}
